### ISSUE TITLE
[Post-to] 받는 사람 이름을 입력한 이후 엔터를 누르면 등록이 안되네요

### ISSUE THREAD

**Issue by Rhajiit** [innerstella/itsBasic#105]
### 엔터를 눌러 submit 하였을때
![SHANA 엔터를 누르면 페이지 등록이 안되요](https://github.com/innerstella/itsBasic/assets/155033024/ec40d418-dca4-446e-b7cf-1d8c110bac3c)

### submit을 한 이후 페이지 리스트를 확인할 때
![image](https://github.com/innerstella/itsBasic/assets/155033024/2b14a0cf-1ced-46ba-b5f0-d1943d6562d0)

## 현재 문제 설명

- 받을 사람 이름을 입력한 이후 엔터를 누르면(submit을 하면) 새로운 롤링페이퍼 페이지가 생성되지 않네요

## TO DO

- 아마 onClick으로 이벤트를 등록해두신것 같은데, onSubmit 설정하고 preventDefault로  새로고침을 막으시거나, button type을 button으로 변경하시면 될 것 같습니다

**Comment by innerstella** [comment]
확인했습니다! 고쳐둘게요!
