### ISSUE TITLE
[최종 발표] 발표 자료 마무리

### ISSUE THREAD

**Issue by innerstella** [innerstella/itsBasic#113]
**다음주 화요일(3/12) 오전 10시~12시,  오후 1시~3시**

발표 세션을 앞두고 몇 가지 안내 사항 전달 드립니다.

발표 준비 사항

### **발표 시 필수로 포함되어야 하는 내용**

- [x] 팀원 소개
- [x] 기능 구현 설명 (대표적으로 몇 가지만)
- [x] 문제 및 해결 방법
- [x] 서비스 시연(데모)
- [x] n팀, 각 팀원명이 모두 적혀있는 표지 + 마지막 q&a 페이지를 꼭 만들어주세요.

발표 자료는 팀별로 편한 방식으로 준비하시면 됩니다. (노션, 깃허브, ppt 등등)

### 당일 발표

- 발표는 A,B,C 반별로 온라인상(zoom)으로 진행되며, 발표 순서는 반별로 공지가 나갈 예정입니다.
- 발표 시간은 최대 10분, q&a 시간은 최대 5분을 넘기지 않도록 진행해주세요.
- 발표 세션은 커뮤니티 매니저가 진행합니다.
- 스프린터 간의 질문은 발표를 진행할 때 채팅방으로 받아볼 예정이에요. 발표자가 q&a까지 이어서 진행해주시면 됩니다.
- 발표자는 발표 후, Q&A 페이지를 띄운 채 Q&A를 진행해주세요. Q&A 시간이 끝나면 화면공유를 종료해주세요.

**Comment by ChoiMHMH** [comment]
다크모드
* 네비게이션 바에 있는 버튼을 눌러 다크모드와 라이트모드를 변경 가능.
* 로컬스토리지에 테마 값을 저장해두어, 새로고침시에도 변경된 모드는 유지
