### ISSUE TITLE
이미지 파일 선택하면 그 이미지 넣기

### ISSUE THREAD

**Issue by innerstella** [innerstella/itsBasic#55]
# ✨ 해결 

- /profile-images 에서 가져오기

# 구현 요구 사항

## 피그마에 작성된 부분

- 프로필 이미지 파일을 선택 하지 않으면 기본이미지를 넣습니다.
<img width="916" alt="image" src="https://github.com/innerstella/itsBasic/assets/77491430/c64fa1c2-ddad-46fd-bd0c-d80573f25774">

## API 

**profileImageURL: string required**

메세지가 사용할 프로필 사진에 대한 URL

## 방법

1. 피그마 방식 : 파일 업로드  (근데 코드잇에서 제공해주는 서버에는 사진 저장이 없음)
<img width="300" alt="image" src="https://github.com/innerstella/itsBasic/assets/77491430/49bbfa35-f873-4510-a5e9-1a846f9db438">

2. API에 맞추기 : 이미지 주소를 입력하게? (너무 불편할 것 같음)
4. 이전 기수들 : 따로 이미지 파일을 업로드하지는 않고 그냥 있는 프로필 이미지들 중에서만 선택
<img width="400" alt="image" src="https://github.com/innerstella/itsBasic/assets/77491430/49cd83f8-f31a-4f0e-953d-ca571d06a07f">

# API 명세

### 엔드포인트

```json
POST /recipients/{recipientId}/messages/
```

URL 파라미터 `recipientId` 대상에게 보내는 메세지 객체를 생성합니다.

### 바디 파라미터

**sender: string required**

메세지를 남긴 사람의 이름.

**profileImageURL: string required**

메세지가 사용할 프로필 사진에 대한 URL.

**relationship: string (**`”친구” | “지인” | “동료” | “가족”`**) required**

롤링 페이퍼 대상과 메세지를 남기는 사람 사이 관계. `”친구” | “지인” | “동료” | “가족”` 중 하나의 값이어야 한다.

**content: string required**
메세지 내용.

**font: string (**`"Noto Sans” | "Pretendard” | "나눔명조” | "나눔손글씨 손편지체”`**) required**

메세지가 사용할 폰트. `"Noto Sans” | "Pretendard” | "나눔명조” | "나눔손글씨 손편지체”` 중 하나의 값이어야 한다.

### 리퀘스트 예시

```json
POST https://rolling-api.vercel.app/0-3/recipients/2/messages/
Content-Type: application/json

{
    "sender": "김하은",
    "relationship": "가족",
    "content": "열심히 일하는 모습 멋있습니다.",
    "font": "Pretendard",
    "profileImageURL": "https://fastly.picsum.photos/id/311/200/200.jpg?hmac=CHiYGYQ3Xpesshw5eYWH7U0Kyl9zMTZLQuRDU4OtyH8"
}
```

**Comment by gaem-gaem** [comment]
저번에 민혁님이 보내주신 다른 기수분들이 하신거랑 인터넷에 또 다른 분들이 하신거 보니까 두 팀 모두
따로 이미지 파일을 업로드하지는 않고 그냥 있는 프로필 이미지들 중에서만 선택하는 걸로 되어있긴 합니당
